name: Build

on:
    push:
        branches: ['*']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
<<<<<<< HEAD
<<<<<<< HEAD
              uses: actions/checkout@v4
=======
              uses: actions/checkout@v2
>>>>>>> df70d6d (ADD: add dockerfile & build+sonar workflow)
=======
              uses: actions/checkout@v4
>>>>>>> d4072aa (feature: add deploy workflow)
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                cache: 'npm'
                node-version: '24'
                cache-dependency-path: package-lock.json
            - name: Install dependencies
              run: npm ci
            - name: Build the project
              run: npm run build
            - name: ESLint
              run: npm run lint